sudo: required
dist: trusty
language: python
python:
- '3.4'
install:
- pip install -r requirements.txt
script:
- python3 -m coverage run --source="." --branch -m pytest --runslow --blender=$(which blender)
after_success: coveralls
before_install:
- openssl aes-256-cbc -K $encrypted_17c9f05fa8f1_key -iv $encrypted_17c9f05fa8f1_iv -in tests/sample-files.tar.gz.enc -out tests/sample-files.tar.gz -d
- tar -xvzf tests/sample-files.tar.gz -C tests/
- sudo apt-get update
- sudo apt-get install blender
